export default {
  ARTICLE_BLOCK_TYPE_TEXT: "ARTICLE_BLOCK_TYPE_TEXT",
  ARTICLE_BLOCK_TYPE_TEXT_HEADING: "ARTICLE_BLOCK_TYPE_TEXT_HEADING",

  /**
   * element = definition
   * element will be bolded
   */
  ARTICLE_BLOCK_TYPE_TEXT_DEFINITION_LIST:
    "ARTICLE_BLOCK_TYPE_TEXT_DEFINITION_LIST",
  ARTICLE_BLOCK_TYPE_CODE: "ARTICLE_BLOCK_TYPE_CODE",
  ARTICLE_BLOCK_TYPE_WEBVIEW: "ARTICLE_BLOCK_TYPE_WEBVIEW"
};
